#!/bin/sh
set +e

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache* >/dev/null 2>&1 || true

if [ -x /etc/init.d/rpcd ]; then
    /etc/init.d/rpcd reload >/dev/null 2>&1 || true
fi

logger -t lpac-esim "LuCI app removed."
exit 0
